name: Deploy to VDS

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: copy file via ssh password
        uses: appleboy/scp-action@v0.1.7
        with:
          host: 3d598a13308b.vps.myjino.ru
          username: otus
          password: ${{ secrets.SSH_PASSWORD }}
          port: 49205
          source: "./deploy.sh,./package.json,./package-lock.json,./src"
          target: /home/otus/project
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 3d598a13308b.vps.myjino.ru
          username: otus
          password: ${{ secrets.SSH_PASSWORD }}
          port: 49205
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            cd /home/otus/project
            npm i
            pm2 restart ./src/index.js
